language: go

go: 
  - tip

before_install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega

install:
  - go get github.com/tools/godep
  - godep restore
  - ginkgo -r --failOnPending --cover --trace --race --compilers=2