language: go

go: 
  - tip

before_install:
 - go get github.com/tools/godep

install:
 - godep restore
 - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2